version: "3.8"
services:
    db:
        image: postgres:13
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: taskdb
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./migrations:/docker-entrypoint-initdb.d

volumes:
    postgres_data:
